version: "3.9"

name: create-user

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - app-network

  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: docker/php
      dockerfile: Dockerfile
    container_name: app-php
    image: app-php:local
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    networks:
      - app-network
    depends_on:
      - nginx
      - db
    command: >
      sh -c "
        while ! nc -z db 3306; do
        echo 'Ждёмс MySQL...';
        sleep 5;
        done;
        composer install --optimize-autoloader --no-scripts --prefer-dist --no-interaction &&
        php artisan migrate &&
        php-fpm
      "

  db:
    build:
      context: docker/db/
      dockerfile: Dockerfile
    container_name: app-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_local_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: app-redis
    restart: unless-stopped
    image: "redis:7.2.4-alpine"
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - container-volume:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  container-volume:
  mysql_local_data:
    external: false
